# Generated by Django 6.0.1 on 2026-01-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Alimentation',
                'verbose_name_plural': 'Alimentations',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.IntegerField(help_text="Début de la période en millions d'années")),
                ('end', models.IntegerField(help_text="Fin de la période en millions d'années")),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
            },
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('taille', models.FloatField(help_text='Taille en mètres')),
                ('poid', models.FloatField(help_text='Poids en kilogrammes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dinosaurs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.alimentation')),
                ('category', models.ManyToManyField(related_name='dinosaurs', to='api.category')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.localisation')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.periode')),
            ],
            options={
                'verbose_name': 'Dinosaure',
                'verbose_name_plural': 'Dinosaures',
            },
        ),
    ]
