# Generated by Django 6.0.1 on 2026-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='end',
            field=models.IntegerField(blank=True, help_text="Fin de la période en millions d'années", null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='start',
            field=models.IntegerField(blank=True, help_text="Début de la période en millions d'années", null=True),
        ),
    ]
