# Generated by Django 6.0.1 on 2026-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_localisation_country_alter_periode_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='dinosaurs', to='api.category'),
        ),
    ]
