# Generated by Django 6.0.1 on 2026-01-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dinosaur_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localisation',
            name='country',
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='alimentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.alimentation', verbose_name='Alimentation'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='dinosaurs', to='api.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dinosaurs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.localisation', verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.periode', verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='poid',
            field=models.FloatField(help_text='Poids en kilogrammes', verbose_name='Poids'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='scientific_name',
            field=models.CharField(max_length=150, verbose_name='Nom scientifique'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='taille',
            field=models.FloatField(help_text='Taille en mètres', verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='continent',
            field=models.CharField(max_length=100, verbose_name='Continent'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
