# Generated by Django 6.0.1 on 2026-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_localisation_country_alter_alimentation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localisation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
    ]
