# Generated by Django 6.0.1 on 2026-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_localisation_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinosaur',
            name='localisation',
        ),
        migrations.AddField(
            model_name='dinosaur',
            name='localisation',
            field=models.ManyToManyField(related_name='dinosaurs', to='api.localisation', verbose_name='Localisation'),
        ),
    ]
