# Generated by Django 6.0.1 on 2026-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_dinosaur_localisation_dinosaur_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='fact',
            field=models.TextField(blank=True, null=True, verbose_name='Fait intéressant'),
        ),
    ]
